// File and folder names often say why something was saved
// ("magus__eddm_door-hanger-strip-magnets.png", "Recipes/pho.png").
// Auto-generated names ("Screenshot 2026-09-07 at 10.20.42 PM", "IMG_2041")
// say nothing. These helpers separate the two.

import { basename, dirname, extname } from "node:path";

/**
 * SQL for a screenshot's name within its source (table alias `s`): the path
 * inside a folder, or the file name Photos reports. A Photos asset id means
 * nothing to people, so it never stands in for a name.
 */
export const NAME_SQL = "COALESCE(s.file_name, s.source_key)";

const AUTO_NAME_PATTERNS: RegExp[] = [
  /^(screenshot|screen shot|cleanshot|simulator screen shot|simulator screenshot)\b/i,
  /^screenshot_\d/i,
  /^(img|dsc|dscn|pxl|mvimg|vid|photo|image|pic)[ _-]?\d+/i,
  /^(image|untitled|unknown|download|capture)( ?\(?\d*\)?)?$/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, // UUID
  /^[\d\s._-]+$/, // only digits and separators
];

// Words that only describe the capture itself, never its subject.
const NOISE = new Set([
  "screenshot", "screen", "shot", "screenshots", "cleanshot", "simulator", "img", "dsc", "dscn", "pxl",
  "image", "photo", "pic", "copy", "final", "untitled", "at", "am", "pm", "2x", "3x",
]);

/** True when the base name was generated by a device or app rather than chosen by a person. */
export function isAutoName(sourceKey: string): boolean {
  const stem = basename(sourceKey, extname(sourceKey)).trim();
  return AUTO_NAME_PATTERNS.some((p) => p.test(stem));
}

/**
 * Meaningful words from the folder path and file name: separators and
 * camelCase split, dates, numbers and capture boilerplate dropped.
 * "Ideas/PickleballWall_v2 (1).png" → "ideas pickleball wall v2".
 */
export function nameTerms(sourceKey: string): string {
  const withoutExt = sourceKey.slice(0, sourceKey.length - extname(sourceKey).length);
  const words = withoutExt
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .toLowerCase()
    .split(/[^\p{L}\p{N}]+/u)
    .filter((w) => w.length > 1 && !/^\d+$/.test(w) && !NOISE.has(w));
  return [...new Set(words)].join(" ");
}

export interface NameHint {
  file_name: string;
  /** Folder path inside the source, if the file isn't at its root. */
  folder: string | null;
  /** False for auto-generated names, which carry no meaning. */
  name_is_descriptive: boolean;
}

export function nameHint(sourceKey: string): NameHint {
  const folder = dirname(sourceKey);
  return {
    file_name: basename(sourceKey),
    folder: folder === "." ? null : folder,
    name_is_descriptive: !isAutoName(sourceKey) && nameTerms(basename(sourceKey)).length > 0,
  };
}
